---
title: "Israel Cycling routes"
author: "by Michael Berger"
date: "12 October 2018"
output: html_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotKML)
library(leaflet)
```
<script src="http://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
<script src="js/leaflet-providers.js"></script>
```{r preprocessing, echo=F, message=F, cache=T}
#setwd('Week 2')



preProcGpx <- function(filename)
{
  DAT <- readGPX(filename)
  DAT <- DAT$tracks[[1]]
  ddat <- DAT[[1]][[1]]
  for (ii in seq(2,length(DAT)))
  {
    ddat <- rbind(ddat,DAT[[ii]])
  }
  #df <- ddat[,c('lat','lon')]
  #df$idx <- as.character(seq(1,372))
  df <- ddat[-1,]
}

files<- list.files(path = '.', pattern = '*.gpx')
dfs <- lapply(files, FUN = preProcGpx)

  
```


Here you can see some circular bycicle routes across northern Israel. You may hide/show individual tracks by selecting them in layers menu in top right corner.  
```{r plotting, echo = F, fig.width=12, fig.height=8}
#
ll<-  leaflet() %>%
  addProviderTiles("Stamen.Terrain") #%>% 
  #addTiles()
  #addLayersControl()%>%

cols <- c('#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#808080', '#ffffff', '#000000') 
#cols<- cols[order(cols, decreasing = F)]
for (ii in 1:length(dfs))
{
  ll<- addPolylines(ll, data = dfs[[ii]], ~lon, ~lat, color=cols[ii], popup=as.character(ii), weight = 2, group = as.character(ii), opacity = 1)
}

ll<-addLayersControl(ll,position = "topright", overlayGroups = as.character(seq(1,length(dfs))))

ll

# hideGroup(ll,'3')
# showGroup(ll,'3')
  #addPolylines(data = dfs[[2]], ~lon, ~lat, color="blue", popup="2", weight = 2)
 # %>%  addPolylines(data = dfs[[3]], ~lon, ~lat, color="blue", popup="3", weight = 2)
 # addPolylines(data = dfs[[4]], ~lon, ~lat, color="blue", popup="4", weight = 2)

```

Track data provided  by [groopy.co.il](http://www.groopy.co.il/tracks.aspx)


