---
title: "Israel Cycling routes"
author: "Michael Berger"
date: "12 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preprocessing, echo=F, message=F, cache=T}
setwd('/home/michael/Studies/Coursera/9 - Developing data products/Week 2/Project/')
library(plotKML)
library(leaflet)


preProcGpx <- function(filename)
{
  DAT <- readGPX(filename)
  DAT <- DAT$tracks[[1]]
  ddat <- DAT[[1]][[1]]
  for (ii in seq(2,length(DAT)))
  {
    ddat <- rbind(ddat,DAT[[ii]])
  }
  #df <- ddat[,c('lat','lon')]
  #df$idx <- as.character(seq(1,372))
  df <- ddat[-1,]
}

files<- list.files(path = getwd(), pattern = '*.gpx')
dfs <- lapply(files, FUN = preProcGpx)

  
```

```{r plotting, echo = F}

ll<-  leaflet() %>%
  addLayersControl()%>%
  addTiles()
cols <- c('#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#808080', '#ffffff', '#000000') 
cols<- cols[order(cols, decreasing = F)]
for (ii in 1:3)#length(dfs))
{
  ll<- addPolylines(ll, data = dfs[[ii]], ~lon, ~lat, color=cols[ii], popup=as.character(ii), weight = 4, group = as.character(ii))
}
ll


hideGroup(ll,'3')
showGroup(ll,'3')
  #addPolylines(data = dfs[[2]], ~lon, ~lat, color="blue", popup="2", weight = 2)
 # %>%  addPolylines(data = dfs[[3]], ~lon, ~lat, color="blue", popup="3", weight = 2)
 # addPolylines(data = dfs[[4]], ~lon, ~lat, color="blue", popup="4", weight = 2)
addLayersControl(maybe)
```

